---
- name: Create group
  group:
    name: "{{ user.group }}"
    state: present
  become: true
  tags: ['user']

- name: Create user
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    groups: "{{ user.groups }}"
    password: "{{ user_password|password_hash('sha512') }}"
    update_password: on_create
  become: true
  tags: ['user']
